services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge