- name: Deploy Docker container
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes
    - name: Pull Nginx image
      docker_image:
        name: nginx
        source: pull
    - name: Run Nginx container
      docker_container:
        name: my_nginx
        image: nginx
        state: started
        ports:
          - "80:80"