name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-docker-app:${{ github.sha }} ./week5/dockerized_app

      - name: Run Docker container
        run: docker run -d -p 8080:80 my-docker-app:${{ github.sha }}

      - name: Test Docker container
        run: |
          sleep 5
          curl -f http://localhost:8080 || exit 1